name: vpn_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  
  provider: ^6.1.5 # Для управления состоянием
  flutter_secure_storage: ^9.2.4 # Для хранения токенов/данных
  intl: ^0.20.2 # Для локализации
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  wireguard_flutter: ^0.1.3
  path_provider: ^2.1.1
  window_size: ^0.1.0 # Добавлено для управления размером окна
  tray_manager: ^0.5.0
  window_manager: ^0.5.0
  logger: ^2.5.0
  http: ^1.4.0 # Для API-запросов
  gif: ^2.3.0
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.5
  yookassa_payments_flutter: ^1.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15 # Для написания тестов
  mockito: ^5.4.4

flutter:
  assets:
    - assets/tray_icon_connect.png
    - assets/tray_icon_connect.ico
    - assets/tray_icon_disconnect.png
    - assets/tray_icon_disconnect.ico
    - assets/dark_theme_vpn_connect.gif
    - assets/dark_theme_vpn_disconnect.gif
    - assets/light_theme_vpn_connect.gif
    - assets/light_theme_vpn_disconnect.gif
  uses-material-design: true
  
