name: vpn_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.2
  wireguard_flutter: ^0.1.3
  path_provider: ^2.1.5
  window_size: ^0.1.0
  tray_manager: ^0.5.0
  window_manager: ^0.5.1
  logger: ^2.6.1
  http: ^1.5.0
  font_awesome_flutter: ^10.9.0
  url_launcher: ^6.3.2
  yookassa_payments_flutter: ^1.9.0
  webview_flutter: ^4.13.0
  device_info_plus: ^11.5.0
  webview_windows: ^0.4.0
  uuid: ^4.5.1
  dio: ^5.9.0
  go_router: ^16.1.0
  meta: ^1.16.0
  gif: ^2.3.0
  connectivity_plus: ^6.1.5
  shared_preferences: ^2.5.3
  app_links: ^6.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.25.15
  mocktail: ^1.0.4

flutter_launcher_icons:
  image_path: "assets/icons/icon_512x512.png"
  android: true
  ios: true
  macos:
    generate: true
    icon_size: 256
  windows:
    generate: true
    icon_size: 256

flutter:
  uses-material-design: true
  assets:
    - assets/tray/tray_icon_connect.ico
    - assets/tray/tray_icon_connect.png
    - assets/tray/tray_icon_disconnect.ico
    - assets/tray/tray_icon_disconnect.png
    - assets/anim/dark/connect.gif
    - assets/anim/dark/disconnect.gif
    - assets/anim/light/connect.gif
    - assets/anim/light/disconnect.gif
    - assets/background.png
    - assets/background_vpn.png
    - assets/icons/about_icon.png
    - assets/icons/icon_512x512.png
