name: vpn_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5 # Для управления состоянием
  flutter_secure_storage: ^9.2.4 # Для хранения токенов/данных
  http: ^1.1.0 # Для API-запросов
  intl: ^0.20.2 # Для локализации
  cupertino_icons: ^1.0.8
  in_app_purchase: ^3.2.3 # Для подписок
  firebase_auth: ^5.5.3 # Для аутентификации
  firebase_core: ^3.13.0 # Для Firebase

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15 # Для написания тестов

flutter:
  uses-material-design: true
