name: vpn_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1 
  flutter_secure_storage: ^9.2.4 # Для хранения токенов/данных
  intl: ^0.20.2 # Для локализации
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  wireguard_flutter: ^0.1.3
  path_provider: ^2.1.1
  window_size: ^0.1.0 
  tray_manager: ^0.5.0
  window_manager: ^0.5.0
  logger: ^2.5.0
  http: ^1.4.0 
  gif: ^2.3.0
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.5
  yookassa_payments_flutter: ^1.9.0
  webview_flutter: ^4.13.0 
  device_info_plus: ^11.5.0
  webview_windows: ^0.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15
  mockito: ^5.4.4

flutter_launcher_icons:
  image_path: "assets/icons/icon_512x512.png"
  android: true
  ios: true
  macos:
    generate: true
    icon_size: 256
  windows:
    generate: true
    icon_size: 256


flutter:
  uses-material-design: true
  assets:
    - assets/tray_icon_connect.png
    - assets/tray_icon_connect.ico
    - assets/tray_icon_disconnect.png
    - assets/tray_icon_disconnect.ico
    - assets/dark_theme_vpn_connect.gif
    - assets/dark_theme_vpn_disconnect.gif
    - assets/light_theme_vpn_connect.gif
    - assets/light_theme_vpn_disconnect.gif
    - assets/background.png
    - assets/background_vpn.png
